const {
  DEFAULT_SERVER_PORT,
  ERROR_MESSAGES,
  PHONE_REG_EXP,
  EMAIL_REG_EXP,
  TEMP_DIR,
  USERS_AVATARS_DIR,
  BASE_URL,
  SENDER_EMAIL,
} = require("./consts");

module.exports = {
  DEFAULT_SERVER_PORT,
  ERROR_MESSAGES,
  PHONE_REG_EXP,
  EMAIL_REG_EXP,
  TEMP_DIR,
  USERS_AVATARS_DIR,
  BASE_URL,
  SENDER_EMAIL,
};
