const {
  DEFAULT_SERVER_PORT,
  ERROR_MESSAGES,
  PHONE_REG_EXP,
  EMAIL_REG_EXP,
  TEMP_DIRECTORY,
  USERS_AVATARS_DIRECTORY,
} = require("./consts");

module.exports = {
  DEFAULT_SERVER_PORT,
  ERROR_MESSAGES,
  PHONE_REG_EXP,
  EMAIL_REG_EXP,
  TEMP_DIRECTORY,
  USERS_AVATARS_DIRECTORY,
};
